### ISSUE TITLE
Passing props to custom components

### ISSUE THREAD

**Issue by KBOE2** [smwbtech/vue-flash-message#10]
I am currently using this great library for a new project.
But I am missing the option to pass props when a custom Component is set.
Also I would like to have the chance to pass an imported component (not a global one) as a custom Component.

Idea:
```vue
<script>
import myCustomFlashMessage from './components/myCustomFlashMessage.vue';
export default {
    ...,
    methods: {
        showFlash() {
            this.flashMessage.success({
                component: myCustomComponent,
                componentProps: {},
            });
        },
    },
};
</script>
```
`myCustomFlashMessage.vue` then receives the props set in `componentProps` (of course the `messageId` too)

Is there a chance for this to be implemented?

Greetings
Jan

**Comment by smwbtech** [comment]
Hi, @KBOE2 

Looks like good idea :) I put it to my to do list.

**Comment by singhgursharnbir** [comment]
Hi any update on this ? I am also looking into using custom component and then passing message as a prop

**Comment by smwbtech** [comment]
Hi @KBOE2  and @singhgursharnbir! First of all, thank you for attention to this project!
I know that there was not enough feedback from my side about this issue, due to my main work and covid situation. 

But finally I got a time. So, to realize this feature I need to rewrite the component as [render function](https://vuejs.org/v2/guide/render-function.html). 

It will take time and may lead to some more changed. I suppose this feature will be implemented with next minor release.
I will not promise about exact terms of implementation, but it will be next thing I'll work on (talking about open source).

Best regards!

**Comment by smwbtech** [comment]
@KBOE2 and @singhgursharnbir 

This feature was implemented in 1.x.x for Vue 3
You can try it out. [For more details](https://www.npmjs.com/package/@smartweb/vue-flash-message/v/next)

0.x.x version will be supported untill Vue 2 goes into unsupported status. 
1.x.x will leave alpha/beta status when all Vue 3 infrastructure will be ready. I'm waiting for vue-test-utils 2 at least.
